#!/usr/bin/env tsx
/**
 * Dogfood QA for the Whiteboard subpath. Simulates a real consumer:
 *   1. Imports `@theokit/ui/whiteboard` resolved via the local dist (after `pnpm build`).
 *   2. Feeds it a JSON scene a Claude / GPT agent could realistically emit.
 *   3. Renders to a static SVG string via React's renderToString (SSR path).
 *   4. Asserts the SVG is well-formed and contains all expected elements.
 *
 * Run with: `pnpm build && pnpm tsx scripts/dogfood-whiteboard.ts`
 */
import * as React from "react";
import { renderToString } from "react-dom/server";

interface ResultEntry {
  name: string;
  ok: boolean;
  detail?: string;
}

const results: ResultEntry[] = [];

function check(name: string, condition: boolean, detail?: string): void {
  results.push({ name, ok: condition, detail });
}

async function main(): Promise<void> {
  // Import from the BUILT subpath, not the source. This is what a real
  // consumer would do — proves the bundle, types, and exports actually work.
  const distPath = new URL("../dist/whiteboard/index.js", import.meta.url).pathname;
  const mod = await import(distPath);
  check("subpath builds and is importable", typeof mod.Whiteboard === "function");

  // JSON scene representative of what an LLM emits for an architecture diagram.
  const llmEmittedScene = {
    version: 1 as const,
    width: 720,
    height: 420,
    background: "#ffffff",
    elements: [
      {
        type: "rect" as const,
        x: 40,
        y: 60,
        w: 160,
        h: 80,
        label: "Client",
        fill: "#dbeafe",
        fillStyle: "hachure" as const,
        stroke: "#1f2937",
      },
      {
        type: "rect" as const,
        x: 280,
        y: 60,
        w: 160,
        h: 80,
        label: "API Gateway",
        fill: "#fef3c7",
        fillStyle: "hachure" as const,
        stroke: "#1f2937",
      },
      {
        type: "ellipse" as const,
        x: 520,
        y: 60,
        w: 160,
        h: 80,
        label: "Database",
        fill: "#dcfce7",
        fillStyle: "hachure" as const,
        stroke: "#1f2937",
      },
      {
        type: "arrow" as const,
        x: 200,
        y: 100,
        to: [280, 100] as [number, number],
        label: "request",
        stroke: "#1f2937",
      },
      {
        type: "arrow" as const,
        x: 440,
        y: 100,
        to: [520, 100] as [number, number],
        label: "query",
        stroke: "#1f2937",
      },
      {
        type: "diamond" as const,
        x: 280,
        y: 220,
        w: 160,
        h: 90,
        label: "Cache hit?",
        stroke: "#1f2937",
      },
      {
        type: "arrow" as const,
        x: 360,
        y: 140,
        to: [360, 220] as [number, number],
        stroke: "#1f2937",
      },
      {
        type: "text" as const,
        x: 40,
        y: 360,
        text: "Architecture sketch generated by an LLM",
        fontSize: 16,
      },
    ],
  };

  const html = renderToString(
    React.createElement(mod.Whiteboard, {
      data: llmEmittedScene,
      "aria-label": "Dogfood architecture diagram",
    }),
  );

  check("SSR renderToString produces output", html.length > 0);
  check("output contains <svg>", html.includes("<svg"));
  check("output contains role=img", html.includes('role="img"'));
  check("aria-label propagates", html.includes("Dogfood architecture diagram"));
  check("no NaN attributes", !html.includes("NaN"));
  check(
    "renders all element labels",
    ["Client", "API Gateway", "Database", "Cache hit?"].every((label) => html.includes(label)),
  );
  check(
    "arrow labels render",
    ["request", "query"].every((l) => html.includes(l)),
  );
  check("text element body renders", html.includes("Architecture sketch generated by an LLM"));
  check("background fill applied", html.includes('fill="#ffffff"'));
  check("data-whiteboard-state=ok", html.includes('data-whiteboard-state="ok"'));

  // Invalid JSON path.
  const invalidHtml = renderToString(
    React.createElement(mod.Whiteboard, { data: { totally: "wrong" } }),
  );
  check(
    "invalid scene renders empty fallback (state=invalid)",
    invalidHtml.includes('data-whiteboard-state="invalid"'),
  );
  check("invalid scene does NOT throw during SSR", invalidHtml.includes("<svg"));

  // Bundle isolation runtime-metric proof.
  const { readFile } = await import("node:fs/promises");
  const barrel = await readFile(new URL("../dist/index.js", import.meta.url).pathname, "utf-8");
  check("barrel dist/index.js does NOT mention roughjs", !barrel.includes("roughjs"));
  check(
    "barrel dist/index.js does NOT mention perfect-freehand",
    !barrel.includes("perfect-freehand"),
  );

  // Report.
  const passed = results.filter((r) => r.ok).length;
  const failed = results.filter((r) => !r.ok);
  process.stdout.write(`\nDogfood Whiteboard — ${passed}/${results.length} passed\n`);
  for (const r of results) {
    process.stdout.write(`  ${r.ok ? "✓" : "✗"} ${r.name}${r.detail ? ` — ${r.detail}` : ""}\n`);
  }
  if (failed.length > 0) {
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
